// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230630032111_AddedPostModel")]
    partial class AddedPostModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Shared.Models.Blog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cbf1695-5b80-4759-b170-207d892cb7a0"),
                            Description = "Description of category 1",
                            Name = "Category 1",
                            ThumbnailImage = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            Id = new Guid("ae303d15-baa8-40c8-ab75-1b50176a8cec"),
                            Description = "Description of category 2",
                            Name = "Category 2",
                            ThumbnailImage = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            Id = new Guid("d52ce8e2-5887-4f28-897d-b450b4510dd6"),
                            Description = "Description of category 3",
                            Name = "Category 3",
                            ThumbnailImage = "uploads/placeholder.jpg"
                        });
                });

            modelBuilder.Entity("Shared.Models.Blog.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thunbnailimage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8671a8d1-9632-481a-a139-c5a260ce2073"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("7cbf1695-5b80-4759-b170-207d892cb7a0"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 1.",
                            PublishDate = "30/06/2023 03:21",
                            Published = false,
                            Thunbnailimage = "uploads/placeholder.jpg",
                            Title = "Primer Post"
                        },
                        new
                        {
                            Id = new Guid("976e66fb-f922-46c1-9888-2734f145f609"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("ae303d15-baa8-40c8-ab75-1b50176a8cec"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 2.",
                            PublishDate = "30/06/2023 03:21",
                            Published = false,
                            Thunbnailimage = "uploads/placeholder.jpg",
                            Title = "Segundo Post"
                        },
                        new
                        {
                            Id = new Guid("ac361cd7-1f95-46e8-9216-4d879fb1c5c7"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("d52ce8e2-5887-4f28-897d-b450b4510dd6"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 3.",
                            PublishDate = "30/06/2023 03:21",
                            Published = false,
                            Thunbnailimage = "uploads/placeholder.jpg",
                            Title = "Tercer Post"
                        },
                        new
                        {
                            Id = new Guid("5c741e22-a811-467c-af9b-ca939e28fdf9"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("7cbf1695-5b80-4759-b170-207d892cb7a0"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 4.",
                            PublishDate = "30/06/2023 03:21",
                            Published = false,
                            Thunbnailimage = "uploads/placeholder.jpg",
                            Title = "Cuarto Post"
                        },
                        new
                        {
                            Id = new Guid("b61ec2dd-8302-4356-be1c-70476bc3c040"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("ae303d15-baa8-40c8-ab75-1b50176a8cec"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 5.",
                            PublishDate = "30/06/2023 03:21",
                            Published = false,
                            Thunbnailimage = "uploads/placeholder.jpg",
                            Title = "Quinto Post"
                        },
                        new
                        {
                            Id = new Guid("557f5c87-7b91-40f0-afb4-c2b47db86411"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("d52ce8e2-5887-4f28-897d-b450b4510dd6"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 6.",
                            PublishDate = "30/06/2023 03:21",
                            Published = false,
                            Thunbnailimage = "uploads/placeholder.jpg",
                            Title = "Sexto Post"
                        });
                });

            modelBuilder.Entity("Shared.Models.Blog.Post", b =>
                {
                    b.HasOne("Shared.Models.Blog.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.Blog.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
