// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Shared.Models.Blog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1e6e821-4a35-42d5-b0f2-2544d7651b03"),
                            Description = "Description of category 1",
                            Name = "Category 1",
                            ThumbnailImage = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            Id = new Guid("7721b335-da37-428a-9e5a-74ed430d38a3"),
                            Description = "Description of category 2",
                            Name = "Category 2",
                            ThumbnailImage = "uploads/placeholder.jpg"
                        },
                        new
                        {
                            Id = new Guid("026749b3-f2a7-41a9-873f-82e9303e9500"),
                            Description = "Description of category 3",
                            Name = "Category 3",
                            ThumbnailImage = "uploads/placeholder.jpg"
                        });
                });

            modelBuilder.Entity("Shared.Models.Blog.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishDate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Thumbnailimage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e921a05-0786-49e7-a15e-3bc8ef1f2196"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("c1e6e821-4a35-42d5-b0f2-2544d7651b03"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 1.",
                            PublishDate = "11/07/2023 11:51",
                            Published = false,
                            Thumbnailimage = "uploads/placeholder.jpg",
                            Title = "Primer Post"
                        },
                        new
                        {
                            Id = new Guid("4f38237f-5a49-4f4f-803c-b51bb503b7c8"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("7721b335-da37-428a-9e5a-74ed430d38a3"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 2.",
                            PublishDate = "11/07/2023 11:51",
                            Published = false,
                            Thumbnailimage = "uploads/placeholder.jpg",
                            Title = "Segundo Post"
                        },
                        new
                        {
                            Id = new Guid("95ce2f22-313e-435f-a33f-6c45fe883fca"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("026749b3-f2a7-41a9-873f-82e9303e9500"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 3.",
                            PublishDate = "11/07/2023 11:51",
                            Published = false,
                            Thumbnailimage = "uploads/placeholder.jpg",
                            Title = "Tercer Post"
                        },
                        new
                        {
                            Id = new Guid("b24e9288-4398-45f9-a3fa-ff574de6e107"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("c1e6e821-4a35-42d5-b0f2-2544d7651b03"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 4.",
                            PublishDate = "11/07/2023 11:51",
                            Published = false,
                            Thumbnailimage = "uploads/placeholder.jpg",
                            Title = "Cuarto Post"
                        },
                        new
                        {
                            Id = new Guid("f30feed2-8421-4197-9542-917c88e62ae5"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("7721b335-da37-428a-9e5a-74ed430d38a3"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 5.",
                            PublishDate = "11/07/2023 11:51",
                            Published = false,
                            Thumbnailimage = "uploads/placeholder.jpg",
                            Title = "Quinto Post"
                        },
                        new
                        {
                            Id = new Guid("7a58f248-f419-4643-b0ee-949f422c61a3"),
                            Author = "Wilson OQuendo",
                            CategoryId = new Guid("026749b3-f2a7-41a9-873f-82e9303e9500"),
                            Content = "",
                            Excerpt = "Este es un extracto del post 6.",
                            PublishDate = "11/07/2023 11:51",
                            Published = false,
                            Thumbnailimage = "uploads/placeholder.jpg",
                            Title = "Sexto Post"
                        });
                });

            modelBuilder.Entity("Shared.Models.Blog.Post", b =>
                {
                    b.HasOne("Shared.Models.Blog.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.Blog.Category", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
